# Makefile to build the MacOS distribution

include config

.PHONY: build install installer

build: build-gui

INSTALL_DIR=./dist/macos
DEPLOY_DIR=./dist/macos/deploy
ARCH= $(shell arch)
MACDEPLOYQT=macdeployqt

build-gui:
	@echo "** Building GUI"
	(cd src; qmake; make)

run:
	(cd ./dist/macos/Grasp.app/Contents/MacOS; ./Grasp)

install:
	@echo "** Installing in $(DEPLOY_DIR)"
	rm -rf $(DEPLOY_DIR)
	mkdir $(DEPLOY_DIR)
	cp -r ./src/Grasp.app $(DEPLOY_DIR)
	$(MACDEPLOYQT) $(DEPLOY_DIR)/Grasp.app # Add Framework
	cp -f $(INSTALL_DIR)/rfsmc.exe $(DEPLOY_DIR)/Grasp.app/Contents/MacOS
	cp -f ./src/options_spec.txt $(DEPLOY_DIR)/Grasp.app/Contents/MacOS
	cp -f $(INSTALL_DIR)/grasp.ini $(DEPLOY_DIR)/Grasp.app/Contents/MacOS
	mkdir $(DEPLOY_DIR)/doc
	cp  doc/Using.md $(DEPLOY_DIR)/doc
	cp -r doc/imgs $(DEPLOY_DIR)/doc
	mkdir $(DEPLOY_DIR)/examples
	cp -r examples/* $(DEPLOY_DIR)/examples
	rm -f $(DEPLOY_DIR)/examples/Makefile
	cp {CHANGES.md,KNOWN-BUGS.md,LICENSE,README.md} $(DEPLOY_DIR)
	ln -s /Applications $(DEPLOY_DIR)/Applications

GRASP_VOLUME=Grasp-$(VERSION)

installer:
	@echo "** Creating disk image"
	hdiutil create -volname $(GRASP_VOLUME) -srcfolder $(DEPLOY_DIR) -ov -format UDZO ./binaries/Grasp-$(VERSION)-$(ARCH).dmg

clean:
	(cd src; qmake; make clean)

clobber: clean
	(cd src; qmake; make distclean)
	rm -rf $(INSTALL_DIR)/Grasp.app
	rm -rf $(INSTALL_DIR)/doc
	rm -rf $(INSTALL_DIR)/examples
	rm -f $(INSTALL_DIR)/{CHANGES.md,KNOWN-BUGS.md,LICENSE,README.md}
