# Makefile to build the Linux distribution

include config

.PHONY: build install installer

build: build-gui

build-gui:
	@echo "** Building GUI"
	(cd src; qmake; make)

run:
	(cd src; ./Grasp)

install: dist
	@echo "** Installing in $(INSTALL_DIR)"
	mkdir -p $(INSTALL_DIR)/bin
	cp ./src/Grasp $(INSTALL_DIR)/bin
	cp ./dist/linux/rfsmc.exe $(INSTALL_DIR)/bin
	mkdir -p $(INSTALL_DIR)/share/grasp
	cp ./dist/linux/grasp.ini $(INSTALL_DIR)/share/grasp/
	cp ./src/options_spec.txt $(INSTALL_DIR)/share/grasp/
	mkdir -p $(INSTALL_DIR)/share/grasp/examples
	cp -r examples/[a-z]* $(INSTALL_DIR)/share/grasp//examples/

clean:
	(cd src; qmake; make clean)

clobber: clean
	(cd src; qmake; make distclean)
	rm -f ./dist/linux/Grasp
	rm -f ./dist/linux/grasp.ini
	rm -f ./dist/linux/options_spec.txt

.PHONY:
.PHONY: dist
