# Makefile to build the MacOS distribution

include config

.PHONY: build install installer

build: build-gui

INSTALL_DIR=./dist/macos
ARCH= $(shell arch)

build-gui:
	@echo "** Building GUI"
	(cd src; qmake; make)

run:
	(cd ./dist/macos/Grasp.app/Contents/MacOS; ./Grasp)

install:
	@echo "** Installing in $(INSTALL_DIR)"
	rm -rf $(INSTALL_DIR)/Grasp.app
	cp -r ./src/Grasp.app $(INSTALL_DIR)
	cp -f $(INSTALL_DIR)/rfsmc.exe $(INSTALL_DIR)/Grasp.app/Contents/MacOS
	cp -r ./src/options_spec.txt $(INSTALL_DIR)/Grasp.app/Contents/MacOS
	cp -r $(INSTALL_DIR)/grasp.ini $(INSTALL_DIR)/Grasp.app/Contents/MacOS
	rm -rf $(INSTALL_DIR)/doc
	mkdir $(INSTALL_DIR)/doc
	cp  doc/Using.md $(INSTALL_DIR)/doc
	cp -r doc/imgs $(INSTALL_DIR)/doc
	rm -rf $(INSTALL_DIR)/examples
	mkdir $(INSTALL_DIR)/examples
	cp -r examples/* $(INSTALL_DIR)/examples
	rm -f $(INSTALL_DIR)/examples/Makefile
	cp {CHANGES.md,KNOWN-BUGS.md,LICENSE,README.md} $(INSTALL_DIR)

GRASP_VOLUME=Grasp-$(VERSION)

installer:
	@echo "** Creating disk image"
	rm -f /tmp/Grasp.dmg
	hdiutil create -size 16m -fs HFS+ -volname "$(GRASP_VOLUME)" /tmp/Grasp.dmg
	hdiutil attach /tmp/Grasp.dmg
	cp -r $(INSTALL_DIR)/Grasp.app /Volumes/$(GRASP_VOLUME)
	ln -s /Applications /Volumes/$(GRASP_VOLUME)/Applications
	cp -r $(INSTALL_DIR)/examples /Volumes/$(GRASP_VOLUME)/Examples
	cp -r $(INSTALL_DIR)/doc /Volumes/$(GRASP_VOLUME)/Documentation
	cp $(INSTALL_DIR)/{CHANGES.md,KNOWN-BUGS.md,LICENSE,README.md,INSTALL} /Volumes/$(GRASP_VOLUME)
	hdiutil detach /Volumes/$(GRASP_VOLUME)
	hdiutil convert /tmp/Grasp.dmg -format UDZO -o /tmp/Grasp_ro.dmg
	@echo "** Copying disk image into ./binaries"
	mkdir -p ./binaries # May not exist on cloned repositories
	mv /tmp/Grasp_ro.dmg ./binaries/Grasp-$(VERSION)-$(ARCH).dmg

clean:
	(cd src; qmake; make clean)

clobber: clean
	(cd src; qmake; make distclean)
	rm -rf $(INSTALL_DIR)/Grasp.app
	rm -rf $(INSTALL_DIR)/doc
	rm -rf $(INSTALL_DIR)/examples
	rm -f $(INSTALL_DIR)/{CHANGES.md,KNOWN-BUGS.md,LICENSE,README.md}

.PHONY:
.PHONY: dist
