# Makefile to build the Linux distribution

include config

.PHONY: build install installer

build: build-gui

build-gui:
	@echo "** Building GUI"
	(cd src; qmake; make)

run:
	(cd src; ./Grasp)

install: 
	@echo "** Creating package tree in $(INSTALL_DIR)"
	cp ./src/Grasp ./dist/linux/grasp/usr/bin
	cp ./dist/linux/grasp.ini ./dist/linux/grasp/usr/share/grasp/
	cp ./src/options_spec.txt ./dist/linux/grasp/usr/share/grasp/
	rm -rf ./dist/linux/grasp/usr/share/grasp/examples/*
	mkdir -p ./dist/linux/grasp/usr/share/grasp/examples
	cp -r examples/[a-z]* ./dist/linux/grasp/usr/share/grasp/examples/

installer:
	(cd ./dist/linux; dpkg-deb --build grasp)
	mv ./dist/linux/grasp.deb ./binaries/grasp-$(VERSION)-x64.deb

clean:
	(cd src; qmake; make clean)

clobber: clean
	(cd src; qmake; make distclean)
	rm -f ./dist/linux/grasp/usr/bin/grasp

.PHONY:
.PHONY: dist
