# Makefile to build the Linux distribution

include config
ARCH=$(shell dpkg --print-architecture)

PKG_NAME="grasp"
PKG_VERSION="1.0.0"
PKG_MAINTAINER="J. Sérot <jocelyn.serot@uca.fr>"
PKG_DESCRIPTION="A Qt-based app for designing for reactive state-machine based programs"
PKG_SECTION="utils"
PKG_PRIORITY="optional"
PKG_ARCH=`dpkg --print-architecture`
PKG_FILE=./dist/linux/grasp/DEBIAN/control

.PHONY: build install installer

build: build-gui

build-gui:
	@echo "** Building GUI"
	(cd src; qmake; make)

run:
	(cd src; ./Grasp)

install: 
	@echo "** Creating package tree in $(INSTALL_DIR)"
	cp ./src/Grasp ./dist/linux/grasp/usr/bin/grasp
	rm -f ./dist/linux/grasp/usr/lib/grasp/rfsmc.exe
	cp $(RFSMC) ./dist/linux/grasp/usr/lib/grasp/rfsmc.exe
	cp ./dist/linux/grasp.ini ./dist/linux/grasp/usr/share/grasp/
	cp ./src/options_spec.txt ./dist/linux/grasp/usr/share/grasp/
	rm -rf ./dist/linux/grasp/usr/share/grasp/examples/*
	mkdir -p ./dist/linux/grasp/usr/share/grasp/examples
	cp -r examples/[a-z]* ./dist/linux/grasp/usr/share/grasp/examples/
	@echo "Package: $(PKG_NAME)" > $(PKG_FILE)
	@echo "Version: $(PKG_VERSION)" >> $(PKG_FILE)
	@echo "Section: $(PKG_SECTION)" >> $(PKG_FILE)
	@echo "Priority: $(PKG_PRIORITY)" >> $(PKG_FILE)
	@echo "Architecture: $(PKG_ARCH)" >> $(PKG_FILE)
	@echo "Maintainer: J. Sérot <jocelyn.serot@uca.fr>" >> $(PKG_FILE)
	@echo "Description: $(PKG_DESCRIPTION)" >> $(PKG_FILE)

installer:
	(cd ./dist/linux; dpkg-deb --build grasp)
	mv ./dist/linux/grasp.deb ./binaries/grasp-$(VERSION)-$(ARCH).deb

clean:
	(cd src; qmake; make clean)

clobber: clean
	(cd src; qmake; make distclean)
	rm -f ./dist/linux/grasp/usr/bin/grasp

.PHONY:
.PHONY: dist
